# Generated by Django 5.1.2 on 2025-01-27 22:38

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farmer_image",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                ("farm_name", models.CharField(default="TG farms", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "farm_category",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("vegetable", "Vegetable"),
                            ("meat_and_seafood", "Meat and Seafood"),
                            ("produce", "Produce"),
                            ("dairy_and_eggs", "Dairy and Eggs"),
                        ],
                        default=["vegetable"],
                        max_length=50,
                    ),
                ),
                ("farm_address", models.TextField(default="Unknown Location")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "farm_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="small",
                        max_length=10,
                    ),
                ),
                ("max_orders", models.PositiveIntegerField(default=2)),
                (
                    "delivery_days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        default=["monday"],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmProduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "produce_categories",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetable"),
                            ("meat_and_seafood", "Meat and Seafood"),
                            ("produce", "Produce"),
                            ("dairy_and_eggs", "Dairy and Eggs"),
                        ],
                        default="vegetables",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("pickup_location", models.TextField(blank=True, null=True)),
                (
                    "produce_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("out of stock", "Out of Stock"),
                        ],
                        default="out of stock",
                        max_length=50,
                    ),
                ),
                (
                    "farmer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/produce/")),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="farmer.farmproduce",
                    ),
                ),
            ],
        ),
    ]
