# Generated by Django 5.1.2 on 2024-11-21 04:05

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farmer_image",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                ("farm_name", models.CharField(default="TG farms", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "farm_category",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("vegetable", "Vegetable"),
                            ("meat_and_seafood", "Meat and Seafood"),
                            ("produce", "Produce"),
                            ("dairy_and_eggs", "Dairy and Eggs"),
                        ],
                        default=["vegetable"],
                        max_length=50,
                    ),
                ),
                ("farm_address", models.TextField(default="Unknown Location")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "farm_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="small",
                        max_length=10,
                    ),
                ),
                ("max_orders", models.PositiveIntegerField(default=2)),
                (
                    "delivery_days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        default=["monday"],
                        max_length=56,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmProduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/produce/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
        ),
    ]
