# Generated by Django 5.1.2 on 2025-02-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_bankaccount_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
