# Generated by Django 5.1.2 on 2024-11-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_alter_farmerprofile_delivery_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmproduce",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="farmproduce",
            name="image",
        ),
        migrations.AddField(
            model_name="farmproduce",
            name="pickup_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmproduce",
            name="produce_categories",
            field=models.CharField(
                choices=[
                    ("vegetable", "Vegetable"),
                    ("meat_and_seafood", "Meat and Seafood"),
                    ("produce", "Produce"),
                    ("dairy_and_eggs", "Dairy and Eggs"),
                ],
                default="vegetables",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="farmproduce",
            name="produce_status",
            field=models.CharField(
                choices=[("available", "Available"), ("out of stock", "Out of Stock")],
                default="out of stock",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ProduceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/produce/")),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="farmer.farmproduce",
                    ),
                ),
            ],
        ),
    ]
