# Generated by Django 5.1.2 on 2025-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_withdrawalrequest_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="bank_code",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="paystack_recipient_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
