# Generated by Django 5.1.2 on 2025-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_remove_bankaccount_bank_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(default="thankgod", max_length=150),
        ),
    ]
