# Generated by Django 5.1.2 on 2025-02-02 09:45

import django.core.validators
import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0005_bankaccount_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                default=12345,
                max_length=20,
                validators=[farmer.models.BankAccount.validate_numeric],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    farmer.models.BankAccount.validate_numeric,
                ],
            ),
        ),
    ]
