# Generated by Django 5.1.2 on 2025-02-02 09:48

import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0006_bankaccount_bank_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                default=1234,
                max_length=20,
                validators=[farmer.models.BankAccount.validate_numeric],
            ),
        ),
    ]
