# Generated by Django 5.1.2 on 2025-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0007_alter_bankaccount_bank_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(default="first bank", max_length=255),
        ),
    ]
