# Generated by Django 5.1.2 on 2025-02-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0008_alter_bankaccount_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to="farmer.farmerprofile",
            ),
        ),
    ]
