# Generated by Django 5.1.2 on 2025-02-02 11:51

import django.db.models.deletion
import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0009_alter_bankaccount_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                default="044",
                max_length=20,
                validators=[farmer.models.BankAccount.validate_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="farmer",
            field=models.ForeignKey(
                default="Access Bank",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to="farmer.farmerprofile",
            ),
        ),
    ]
