# Generated by Django 5.1.2 on 2025-02-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0010_alter_bankaccount_bank_code_alter_bankaccount_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(default="Access Bank", max_length=255),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to="farmer.farmerprofile",
            ),
        ),
    ]
