# Generated by Django 5.1.2 on 2025-02-02 12:29

import django.core.validators
import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0011_alter_bankaccount_bank_name_alter_bankaccount_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                default="3079717880",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    farmer.models.BankAccount.validate_numeric,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                default="011",
                max_length=20,
                validators=[farmer.models.BankAccount.validate_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(default="first bank", max_length=255),
        ),
    ]
