# Generated by Django 5.1.2 on 2025-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0012_alter_bankaccount_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="paystack_recipient_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
