# Generated by Django 5.1.2 on 2025-02-02 13:23

import django.core.validators
import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0013_alter_bankaccount_paystack_recipient_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                default="0000000000",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    farmer.models.BankAccount.validate_numeric,
                ],
            ),
        ),
    ]
