# Generated by Django 5.1.2 on 2025-02-02 14:54

import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0014_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(
                default="057",
                max_length=20,
                validators=[farmer.models.BankAccount.validate_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(default="Zenith Test", max_length=255),
        ),
    ]
