# Generated by Django 5.1.2 on 2025-02-06 07:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0015_alter_bankaccount_bank_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerprofile",
            name="farm_category",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("vegetable", "Vegetable"),
                    ("meat_and_seafood", "Meat and Seafood"),
                    ("root_and_tubers", "Root and Tubers"),
                    ("dairy_and_eggs", "Dairy and Eggs"),
                ],
                default=["vegetable"],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="farmproduce",
            name="farmer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm_produce",
                to="farmer.farmerprofile",
            ),
        ),
    ]
