# Generated by Django 5.1.2 on 2025-02-14 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0016_alter_farmerprofile_farm_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmproduce",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
