# Generated by Django 5.1.2 on 2025-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0017_farmproduce_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmproduce",
            name="produce_categories",
            field=models.CharField(
                choices=[
                    ("vegetable", "Vegetable"),
                    ("meat_and_seafood", "Meat and Seafood"),
                    ("root_and_tubers", "Root_and_Tubers"),
                    ("dairy_and_eggs", "Dairy and Eggs"),
                ],
                default="vegetables",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="farmproduce",
            name="produce_status",
            field=models.CharField(
                choices=[("available", "Available"), ("out of stock", "Out of Stock")],
                default="available",
                max_length=50,
            ),
        ),
    ]
