"""
Django settings for Farm_Meet project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


from datetime import timedelta
import dj_database_url
import os
from pathlib import Path
import environ
from celery.schedules import crontab

# from dotenv import load_dotenv

# # Load environment variables from .env file
# load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent


# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, 'api.env')
                     )  # Explicitly load .env file
# Required environment variables
REQUIRED_ENV_VARS = [
    'FLW_SECRET_KEY',
    'FLW_PUBLIC_KEY',
    'FLW_ENCRYPTION_KEY',
    'FLW_BASE_URL',
    'DATABASE_PASSWORD'
]

# Check if all required environment variables are set
missing_vars = [var for var in REQUIRED_ENV_VARS if not env(var, default=None)]

if missing_vars:
    raise RuntimeError(
        f"The following required environment variables are missing: {', '.join(missing_vars)}"
    )

# Flutterwave API Keys
FLW_SECRET_KEY = env('FLW_SECRET_KEY')
FLW_PUBLIC_KEY = env('FLW_PUBLIC_KEY')
FLW_ENCRYPTION_KEY = env('FLW_ENCRYPTION_KEY')
FLW_BASE_URL = env('FLW_BASE_URL', default='https://api.flutterwave.com/v3')


# DATABASE_PASSWORD
DATABASE_PASSWORD = env('DATABASE_PASSWORD')


# Bind to the port from the environment variable or default to 10000
# PORT = int(os.getenv('PORT', 8000))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9ax3-*3!_h_hmu4l%nos^bqyjl18(5v8m1zu(j*!)lm+vzme0a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_celery_beat',
    'django_celery_results',


    # Custom apps
    'users',
    'farmer',
    'customer',
    'orders',
    'wallet'
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
REDIS_URL = os.getenv("REDIS_URL", "rediss://red-ct6u173qf0us738mhc6g:Y9fScVn77uTUNbbXCHnInVgs3NqJy0HU@ohio-redis.render.com:6379")

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,  # Ensure REDIS_URL is correct
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SSL': True, 
        }
    }
}




ALLOWED_HOSTS = ["*"]

ROOT_URLCONF = "Farm_Meet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Farm_Meet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {

# }

# DATABASES["default"] = dj_database_url.parse(
#     "postgresql://farm_meet_wx1e_user:mlddIzLB9NUXNBKnH7PGPPJZULil0HZW@dpg-cv0o5epopnds73ddotp0-a.ohio-postgres.render.com/farm_meet_wx1e")


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': 'pg-3fcf5e6d-mudnoethankgod-d39d.c.aivencloud.com',
        'PORT': '20076',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        'OPTIONS': {'min_length': 6},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.TokenAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    # It will work instead of the default serializer(TokenObtainPairSerializer).
    "TOKEN_OBTAIN_SERIALIZER": "users.serializers.CustomTokenObtainPairSerializer",
}

# Social Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/user.phonenumbers.read',
        ],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'user_mobile_phone'],
        'FIELDS': ['id', 'email', 'name', 'first_name', 'last_name', 'phone'],
    },
}

# Allauth Email and Redirect Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
LOGIN_REDIRECT_URL = '/'

# Media files (images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# settings.py
CELERY_BEAT_SCHEDULE = {
    'check-due-orders': {
        'task': 'orders.tasks.check_due_orders',
        'schedule': crontab(hour=8, minute=0),  # Run daily at 8 AM
    },
    'check-overdue-orders': {
        'task': 'orders.tasks.check_overdue_orders',
        'schedule': crontab(hour=9, minute=0),  # Run daily at 9 AM
    },
}
# SMS
AFRICASTALKING_USERNAME = 'sandbox'
AFRICASTALKING_API_KEY = 'atsk_f99b550848e98e1cf4f40b7146064f9855cdca7a79780081afc1174d50d13d65b0ed7ae5'

# add corsheaders

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8081',
]

SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'

PAYSTACK_SECRET_KEY = "sk_test_c769538a9967bf72da362d64b106778ee21d61b1"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'delivery.log',
        },
    },
    'loggers': {
        'orders': {  # Replace with your app name
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Celery Configuration
CELERY_BROKER_URL = "amqps://xxswwlik:SLPhNnjYjBJ1RcZkVBUV5srjYCf6GNo-@leopard.lmq.cloudamqp.com/xxswwlik"
CELERY_RESULT_BACKEND = "amqps://xxswwlik:SLPhNnjYjBJ1RcZkVBUV5srjYCf6GNo-@leopard.lmq.cloudamqp.com/xxswwlik"
# "amqp://guest:guest@localhost:5672//"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
# # Get Redis URL from environment variable or use default for local development


# CELERY_BROKER_URL = 'django://'
# CELERY_RESULT_BACKEND = 'django-db'
# Additional Celery settings for better reliability
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_POOL_LIMIT = None