# Generated by Django 5.1.2 on 2024-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("farmer", "Farmer"), ("customer", "Customer")],
                default="farmer",
                max_length=10,
            ),
        ),
    ]
