# Generated by Django 5.1.2 on 2025-01-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
        ("orders", "0002_alter_orderitem_delivery_status"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_wallet",
                to="orders.orderitem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="farmer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_wallet",
                to="farmer.farmerprofile",
            ),
        ),
    ]
