# Generated by Django 5.1.2 on 2025-01-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallet_order_alter_wallet_farmer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="order",
        ),
    ]
