databases:
  - name: Farm_Meet
    plan: free
    databaseName: Farm-Meet
    user: Farm_Meet

services:
  - type: web
    plan: free
    name: Farm_Meet
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Farm_Meet.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Farm-Meetdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4