# Generated by Django 5.1.2 on 2024-11-22 05:53

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerprofile",
            name="delivery_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                default=["monday"],
                max_length=50,
            ),
        ),
    ]
