# Generated by Django 5.1.2 on 2025-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("successful", "successful"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]
