# Generated by Django 5.1.2 on 2025-01-31 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
        ("orders", "0003_alter_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_notifications",
                to="farmer.farmerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_order",
                to="farmer.farmerprofile",
            ),
        ),
    ]
