# Generated by Django 5.1.2 on 2025-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_notification_farmer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("successful", "successful"),
                    ("failed", "failed"),
                    ("verified", "verified"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
