# Generated by Django 5.1.2 on 2025-01-31 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["delivery_date"]},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="farmer",
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item_notifications",
                to="orders.orderitem",
            ),
        ),
    ]
