# Generated by Django 5.1.2 on 2025-01-31 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderitem_options_remove_notification_farmer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item_notifications",
                to="orders.orderitem",
            ),
        ),
    ]
